apiVersion: v1
kind: Service
metadata:
  name: shestera-scaletestapp-service
spec:
  type: NodePort
  selector:
    app: shestera-scaletestapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
